### ISSUE TITLE
How to include this?

### ISSUE THREAD

**Issue by TannerS** [RobinBuschmann/express-soap#1]
I see the format

import {soap} from 'express-soap';

which does not work for my node (newest version) it cannot recognize the format

**Comment by RobinBuschmann** [comment]
You need to use a transpiler like babel or typescript for getting this syntax to work or you could use it like so: `const {soap} = require('express-soap')` or `var expressSoap = require('express-soap'); expressSoap.soap`

**Comment by RobinBuschmann** [comment]
Did you get it to work? Or do you need some further help? :)

**Comment by TannerS** [comment]
I got it. Thanks do much
