### ISSUE TITLE
Incorrect express peer dependency defined in package.json

### ISSUE THREAD

**Issue by NicholasMiller** [RobinBuschmann/express-soap#2]
Hello and thanks for publishing this library. When I installed this library, `yarn` complained that I needed express 3.20.0 because you have it listed as a peer dependency. However, when using 3.20.0 with this library it does not work. Using 4.x works as expected.

**Comment by RobinBuschmann** [comment]
Thanks for reporting. I'll check this

**Comment by henryjw** [comment]
I had the same issue. I had 4.x installed and it worked fine. Then I downgraded to 3.21.2 because of the warning, but it stopped working so now I'm back on 4.x.
