### ISSUE TITLE
Build includes ts files

### ISSUE THREAD

**Issue by lennu** [RobinBuschmann/express-soap#4]
Hey thanks for great module.

**Usually** only the built files js, d.ts are included in the module. Now there are both ts and js files some extra configuration is needed for this particular module.

Is this intended?

Included files can be specified with 'files': [] in the package.json.
https://docs.npmjs.com/files/package.json#files

**Comment by RobinBuschmann** [comment]
Sry, for the late reply and thanks for bringing this up. No this is not intended.
