### ISSUE TITLE
How to validate incoming requet? returnFault option does not validate the object request

### ISSUE THREAD

**Issue by crzuniga** [RobinBuschmann/express-soap#7]
I would like to validate the incoming request and return Fault when errors were found, but the **returnFault** option does nothing.

**Comment by RobinBuschmann** [comment]
As far as I understand [node-soap](https://github.com/vpulim/node-soap) correctly, it need to be done manually. So there doesn't seem to happen any validation based on the WSDL

**Comment by crzuniga** [comment]
Thanks
